name: Update readme with blog posts
on:
  workflow_dispatch: 
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://khalidabuhakmeh.com/rss.xml
          readme-section: feed
          max: 10 # max number of items (default 5)
          template: "- **[{{ title }}]({{ link | safe }})**\n"
